server.port=${SERVER_PORT:8080}
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/controle-financeiro}
spring.data.mongodb.auto-index-creation=true
mongock.migration-scan-package=task2.registro_movimentacoes.changelogs

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:barbara.leidemer@universo.univates.br}
spring.mail.password=${MAIL_PASSWORD:xqqmjlkllwdmmzfy}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
