spring.data.mongodb.uri=mongodb://localhost:27017/controle-financeiro
spring.data.mongodb.auto-index-creation=true
mongock.migration-scan-package=task2.registro_movimentacoes.changelogs

# Configurações de E-mail 
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=barbara.leidemer@universo.univates.br
spring.mail.password=xqqmjlkllwdmmzfy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true